#pragma once
#include "aumMonitorableAudioUnit.h"

/******************************************************************************/
/* WARNING: THIS CLASS WAS GENERATED BY THE FOLLOWING FUNCTION:               */
/*                                                                            */
/*     aumUnit_Generic::generateClassFileForAudioUnit(string deviceName);     */
/*                                                                            */
/* IF YOU EDIT THIS FILE, YOU RISK HAVING YOUR CHANGES OVERWRITTEN THE NEXT   */
/* TIME THE FILE IS RE-WRITTEN BY THIS FUNCTION. TO EDIT THIS FILE, PLEASE    */
/* COPY IT TO ANY OTHER FOLDER, RENAME THE CLASS, AND THEN MAKE EDITS.        */
/******************************************************************************/

class aumUnit_AULowPassFilter : public aumMonitorableAudioUnit
{
public:
    //Cutoff Frequency
    //min: 10, max: 21829.5, default: 6900
    const static int cutoff_frequency = 0;

    //Resonance
    //min: -20, max: 40, default: 0
    const static int resonance = 1;

    //These variables store the most recenty recorded values
    //of each of the parameters, for recording and detection
    AudioUnitParameterValue previous_cutoff_frequency;
    AudioUnitParameterValue previous_resonance;

    void setup(string _unitName) {
        aumManagedAudioUnit::setup(_unitName, 'aufx', 'lpas', 'appl', "aumUnit_AULowPassFilter");
    }

    void doPrintChanges() {
        compareAndPrint("cutoff_frequency", previous_cutoff_frequency, get(cutoff_frequency));
        compareAndPrint("resonance", previous_resonance, get(resonance));
    }

    void doRecordParams() {
        previous_cutoff_frequency = get(cutoff_frequency);
        previous_resonance = get(resonance);
    }
};